import 'package:bloc_break_error/blocs/test_bloc_1.dart';
import 'package:bloc_break_error/blocs/test_bloc_2.dart';
import 'package:bloc_break_error/blocs/test_bloc_3.dart';
import 'package:bloc_break_error/blocs/test_bloc_4.dart';
import 'package:bloc_break_error/blocs/test_bloc_5.dart';
import 'package:bloc_break_error/blocs/test_bloc_6.dart';
import 'package:bloc_break_error/blocs/test_bloc_7.dart';
import 'package:bloc_break_error/blocs/test_bloc_8.dart';
import 'package:bloc_break_error/blocs/test_bloc_9.dart';
import 'package:bloc_break_error/blocs/test_bloc_10.dart';
import 'package:bloc_break_error/blocs/test_bloc_11.dart';
import 'package:bloc_break_error/blocs/test_bloc_12.dart';
import 'package:bloc_break_error/blocs/test_bloc_13.dart';
import 'package:bloc_break_error/blocs/test_bloc_14.dart';
import 'package:bloc_break_error/blocs/test_bloc_15.dart';
import 'package:bloc_break_error/blocs/test_bloc_16.dart';
import 'package:bloc_break_error/blocs/test_bloc_17.dart';
import 'package:bloc_break_error/blocs/test_bloc_18.dart';
import 'package:bloc_break_error/blocs/test_bloc_19.dart';
import 'package:bloc_break_error/blocs/test_bloc_20.dart';
import 'package:bloc_break_error/blocs/test_bloc_21.dart';
import 'package:bloc_break_error/blocs/test_bloc_22.dart';
import 'package:bloc_break_error/blocs/test_bloc_23.dart';
import 'package:bloc_break_error/blocs/test_bloc_24.dart';
import 'package:bloc_break_error/blocs/test_bloc_25.dart';
import 'package:bloc_break_error/blocs/test_bloc_26.dart';
import 'package:bloc_break_error/blocs/test_bloc_27.dart';
import 'package:bloc_break_error/blocs/test_bloc_28.dart';
import 'package:bloc_break_error/blocs/test_bloc_29.dart';
import 'package:bloc_break_error/blocs/test_bloc_30.dart';
import 'package:bloc_break_error/blocs/test_bloc_31.dart';
import 'package:bloc_break_error/blocs/test_bloc_32.dart';
import 'package:bloc_break_error/blocs/test_bloc_33.dart';
import 'package:bloc_break_error/blocs/test_bloc_34.dart';
import 'package:bloc_break_error/blocs/test_bloc_35.dart';
import 'package:bloc_break_error/blocs/test_bloc_36.dart';
import 'package:bloc_break_error/blocs/test_bloc_37.dart';
import 'package:bloc_break_error/blocs/test_bloc_38.dart';
import 'package:bloc_break_error/blocs/test_bloc_39.dart';
import 'package:bloc_break_error/blocs/test_bloc_40.dart';
import 'package:bloc_break_error/blocs/test_bloc_41.dart';
import 'package:bloc_break_error/blocs/test_bloc_42.dart';
import 'package:bloc_break_error/blocs/test_bloc_43.dart';
import 'package:bloc_break_error/blocs/test_bloc_44.dart';
import 'package:bloc_break_error/blocs/test_bloc_45.dart';
import 'package:bloc_break_error/blocs/test_bloc_46.dart';
import 'package:bloc_break_error/blocs/test_bloc_47.dart';
import 'package:bloc_break_error/blocs/test_bloc_48.dart';
import 'package:bloc_break_error/blocs/test_bloc_49.dart';
import 'package:bloc_break_error/blocs/test_bloc_50.dart';
import 'package:bloc_break_error/blocs/test_bloc_51.dart';
import 'package:bloc_break_error/blocs/test_bloc_52.dart';
import 'package:bloc_break_error/blocs/test_bloc_53.dart';
import 'package:bloc_break_error/blocs/test_bloc_54.dart';
import 'package:bloc_break_error/blocs/test_bloc_55.dart';
import 'package:bloc_break_error/blocs/test_bloc_56.dart';
import 'package:bloc_break_error/blocs/test_bloc_57.dart';
import 'package:bloc_break_error/blocs/test_bloc_58.dart';
import 'package:bloc_break_error/blocs/test_bloc_59.dart';
import 'package:bloc_break_error/blocs/test_bloc_60.dart';
import 'package:bloc_break_error/blocs/test_bloc_61.dart';
import 'package:bloc_break_error/blocs/test_bloc_62.dart';
import 'package:bloc_break_error/blocs/test_bloc_63.dart';
import 'package:bloc_break_error/blocs/test_bloc_64.dart';
import 'package:bloc_break_error/blocs/test_bloc_65.dart';
import 'package:bloc_break_error/blocs/test_bloc_66.dart';
import 'package:bloc_break_error/blocs/test_bloc_67.dart';
import 'package:bloc_break_error/blocs/test_bloc_68.dart';
import 'package:bloc_break_error/blocs/test_bloc_69.dart';
import 'package:bloc_break_error/blocs/test_bloc_70.dart';
import 'package:bloc_break_error/blocs/test_bloc_71.dart';
import 'package:bloc_break_error/blocs/test_bloc_72.dart';
import 'package:bloc_break_error/blocs/test_bloc_73.dart';
import 'package:bloc_break_error/blocs/test_bloc_74.dart';
import 'package:bloc_break_error/blocs/test_bloc_75.dart';
import 'package:bloc_break_error/blocs/test_bloc_76.dart';
import 'package:bloc_break_error/blocs/test_bloc_77.dart';
import 'package:bloc_break_error/blocs/test_bloc_78.dart';
import 'package:bloc_break_error/blocs/test_bloc_79.dart';
import 'package:bloc_break_error/blocs/test_bloc_80.dart';
import 'package:bloc_break_error/blocs/test_bloc_81.dart';
import 'package:bloc_break_error/blocs/test_bloc_82.dart';
import 'package:bloc_break_error/blocs/test_bloc_83.dart';
import 'package:bloc_break_error/blocs/test_bloc_84.dart';
import 'package:bloc_break_error/blocs/test_bloc_85.dart';
import 'package:bloc_break_error/blocs/test_bloc_86.dart';
import 'package:bloc_break_error/blocs/test_bloc_87.dart';
import 'package:bloc_break_error/blocs/test_bloc_88.dart';
import 'package:bloc_break_error/blocs/test_bloc_89.dart';
import 'package:bloc_break_error/blocs/test_bloc_90.dart';
import 'package:bloc_break_error/blocs/test_bloc_91.dart';
import 'package:bloc_break_error/blocs/test_bloc_92.dart';
import 'package:bloc_break_error/blocs/test_bloc_93.dart';
import 'package:bloc_break_error/blocs/test_bloc_94.dart';
import 'package:bloc_break_error/blocs/test_bloc_95.dart';
import 'package:bloc_break_error/blocs/test_bloc_96.dart';
import 'package:bloc_break_error/blocs/test_bloc_97.dart';
import 'package:bloc_break_error/blocs/test_bloc_98.dart';
import 'package:bloc_break_error/blocs/test_bloc_99.dart';
import 'package:bloc_break_error/blocs/test_bloc_100.dart';
import 'package:bloc_break_error/blocs/test_bloc_101.dart';
import 'package:bloc_break_error/blocs/test_bloc_102.dart';
import 'package:bloc_break_error/blocs/test_bloc_103.dart';
import 'package:bloc_break_error/blocs/test_bloc_104.dart';
import 'package:bloc_break_error/blocs/test_bloc_105.dart';
import 'package:bloc_break_error/blocs/test_bloc_106.dart';
import 'package:bloc_break_error/blocs/test_bloc_107.dart';
import 'package:bloc_break_error/blocs/test_bloc_108.dart';
import 'package:bloc_break_error/blocs/test_bloc_109.dart';
import 'package:bloc_break_error/blocs/test_bloc_110.dart';
import 'package:bloc_break_error/blocs/test_bloc_111.dart';
import 'package:bloc_break_error/blocs/test_bloc_112.dart';
import 'package:bloc_break_error/blocs/test_bloc_113.dart';
import 'package:bloc_break_error/blocs/test_bloc_114.dart';
import 'package:bloc_break_error/blocs/test_bloc_115.dart';
import 'package:bloc_break_error/blocs/test_bloc_116.dart';
import 'package:bloc_break_error/blocs/test_bloc_117.dart';
import 'package:bloc_break_error/blocs/test_bloc_118.dart';
import 'package:bloc_break_error/blocs/test_bloc_119.dart';
import 'package:bloc_break_error/blocs/test_bloc_120.dart';
import 'package:bloc_break_error/blocs/test_bloc_121.dart';
import 'package:bloc_break_error/blocs/test_bloc_122.dart';
import 'package:bloc_break_error/blocs/test_bloc_123.dart';
import 'package:bloc_break_error/blocs/test_bloc_124.dart';
import 'package:bloc_break_error/blocs/test_bloc_125.dart';
import 'package:bloc_break_error/blocs/test_bloc_126.dart';
import 'package:bloc_break_error/blocs/test_bloc_127.dart';
import 'package:bloc_break_error/blocs/test_bloc_128.dart';
import 'package:bloc_break_error/blocs/test_bloc_129.dart';
import 'package:bloc_break_error/blocs/test_bloc_130.dart';
import 'package:bloc_break_error/blocs/test_bloc_131.dart';
import 'package:bloc_break_error/blocs/test_bloc_132.dart';
import 'package:bloc_break_error/blocs/test_bloc_133.dart';
import 'package:bloc_break_error/blocs/test_bloc_134.dart';
import 'package:bloc_break_error/blocs/test_bloc_135.dart';
import 'package:bloc_break_error/blocs/test_bloc_136.dart';
import 'package:bloc_break_error/blocs/test_bloc_137.dart';
import 'package:bloc_break_error/blocs/test_bloc_138.dart';
import 'package:bloc_break_error/blocs/test_bloc_139.dart';
import 'package:bloc_break_error/blocs/test_bloc_140.dart';
import 'package:bloc_break_error/blocs/test_bloc_141.dart';
import 'package:bloc_break_error/blocs/test_bloc_142.dart';
import 'package:bloc_break_error/blocs/test_bloc_143.dart';
import 'package:bloc_break_error/blocs/test_bloc_144.dart';
import 'package:bloc_break_error/blocs/test_bloc_145.dart';
import 'package:bloc_break_error/blocs/test_bloc_146.dart';
import 'package:bloc_break_error/blocs/test_bloc_147.dart';
import 'package:bloc_break_error/blocs/test_bloc_148.dart';
import 'package:bloc_break_error/blocs/test_bloc_149.dart';
import 'package:bloc_break_error/blocs/test_bloc_150.dart';
import 'package:get_it/get_it.dart';

final locator = GetIt.instance;

void initLocator() {
  locator.registerLazySingleton(() => Test1Bloc());
  locator.registerLazySingleton(() => Test2Bloc());
  locator.registerLazySingleton(() => Test3Bloc());
  locator.registerLazySingleton(() => Test4Bloc());
  locator.registerLazySingleton(() => Test5Bloc());
  locator.registerLazySingleton(() => Test6Bloc());
  locator.registerLazySingleton(() => Test7Bloc());
  locator.registerLazySingleton(() => Test8Bloc());
  locator.registerLazySingleton(() => Test9Bloc());
  locator.registerLazySingleton(() => Test10Bloc());
  locator.registerLazySingleton(() => Test11Bloc());
  locator.registerLazySingleton(() => Test12Bloc());
  locator.registerLazySingleton(() => Test13Bloc());
  locator.registerLazySingleton(() => Test14Bloc());
  locator.registerLazySingleton(() => Test15Bloc());
  locator.registerLazySingleton(() => Test16Bloc());
  locator.registerLazySingleton(() => Test17Bloc());
  locator.registerLazySingleton(() => Test18Bloc());
  locator.registerLazySingleton(() => Test19Bloc());
  locator.registerLazySingleton(() => Test20Bloc());
  locator.registerLazySingleton(() => Test21Bloc());
  locator.registerLazySingleton(() => Test22Bloc());
  locator.registerLazySingleton(() => Test23Bloc());
  locator.registerLazySingleton(() => Test24Bloc());
  locator.registerLazySingleton(() => Test25Bloc());
  locator.registerLazySingleton(() => Test26Bloc());
  locator.registerLazySingleton(() => Test27Bloc());
  locator.registerLazySingleton(() => Test28Bloc());
  locator.registerLazySingleton(() => Test29Bloc());
  locator.registerLazySingleton(() => Test30Bloc());
  locator.registerLazySingleton(() => Test31Bloc());
  locator.registerLazySingleton(() => Test32Bloc());
  locator.registerLazySingleton(() => Test33Bloc());
  locator.registerLazySingleton(() => Test34Bloc());
  locator.registerLazySingleton(() => Test35Bloc());
  locator.registerLazySingleton(() => Test36Bloc());
  locator.registerLazySingleton(() => Test37Bloc());
  locator.registerLazySingleton(() => Test38Bloc());
  locator.registerLazySingleton(() => Test39Bloc());
  locator.registerLazySingleton(() => Test40Bloc());
  locator.registerLazySingleton(() => Test41Bloc());
  locator.registerLazySingleton(() => Test42Bloc());
  locator.registerLazySingleton(() => Test43Bloc());
  locator.registerLazySingleton(() => Test44Bloc());
  locator.registerLazySingleton(() => Test45Bloc());
  locator.registerLazySingleton(() => Test46Bloc());
  locator.registerLazySingleton(() => Test47Bloc());
  locator.registerLazySingleton(() => Test48Bloc());
  locator.registerLazySingleton(() => Test49Bloc());
  locator.registerLazySingleton(() => Test50Bloc());
  locator.registerLazySingleton(() => Test51Bloc());
  locator.registerLazySingleton(() => Test52Bloc());
  locator.registerLazySingleton(() => Test53Bloc());
  locator.registerLazySingleton(() => Test54Bloc());
  locator.registerLazySingleton(() => Test55Bloc());
  locator.registerLazySingleton(() => Test56Bloc());
  locator.registerLazySingleton(() => Test57Bloc());
  locator.registerLazySingleton(() => Test58Bloc());
  locator.registerLazySingleton(() => Test59Bloc());
  locator.registerLazySingleton(() => Test60Bloc());
  locator.registerLazySingleton(() => Test61Bloc());
  locator.registerLazySingleton(() => Test62Bloc());
  locator.registerLazySingleton(() => Test63Bloc());
  locator.registerLazySingleton(() => Test64Bloc());
  locator.registerLazySingleton(() => Test65Bloc());
  locator.registerLazySingleton(() => Test66Bloc());
  locator.registerLazySingleton(() => Test67Bloc());
  locator.registerLazySingleton(() => Test68Bloc());
  locator.registerLazySingleton(() => Test69Bloc());
  locator.registerLazySingleton(() => Test70Bloc());
  locator.registerLazySingleton(() => Test71Bloc());
  locator.registerLazySingleton(() => Test72Bloc());
  locator.registerLazySingleton(() => Test73Bloc());
  locator.registerLazySingleton(() => Test74Bloc());
  locator.registerLazySingleton(() => Test75Bloc());
  locator.registerLazySingleton(() => Test76Bloc());
  locator.registerLazySingleton(() => Test77Bloc());
  locator.registerLazySingleton(() => Test78Bloc());
  locator.registerLazySingleton(() => Test79Bloc());
  locator.registerLazySingleton(() => Test80Bloc());
  locator.registerLazySingleton(() => Test81Bloc());
  locator.registerLazySingleton(() => Test82Bloc());
  locator.registerLazySingleton(() => Test83Bloc());
  locator.registerLazySingleton(() => Test84Bloc());
  locator.registerLazySingleton(() => Test85Bloc());
  locator.registerLazySingleton(() => Test86Bloc());
  locator.registerLazySingleton(() => Test87Bloc());
  locator.registerLazySingleton(() => Test88Bloc());
  locator.registerLazySingleton(() => Test89Bloc());
  locator.registerLazySingleton(() => Test90Bloc());
  locator.registerLazySingleton(() => Test91Bloc());
  locator.registerLazySingleton(() => Test92Bloc());
  locator.registerLazySingleton(() => Test93Bloc());
  locator.registerLazySingleton(() => Test94Bloc());
  locator.registerLazySingleton(() => Test95Bloc());
  locator.registerLazySingleton(() => Test96Bloc());
  locator.registerLazySingleton(() => Test97Bloc());
  locator.registerLazySingleton(() => Test98Bloc());
  locator.registerLazySingleton(() => Test99Bloc());
  locator.registerLazySingleton(() => Test100Bloc());
  locator.registerLazySingleton(() => Test101Bloc());
  locator.registerLazySingleton(() => Test102Bloc());
  locator.registerLazySingleton(() => Test103Bloc());
  locator.registerLazySingleton(() => Test104Bloc());
  locator.registerLazySingleton(() => Test105Bloc());
  locator.registerLazySingleton(() => Test106Bloc());
  locator.registerLazySingleton(() => Test107Bloc());
  locator.registerLazySingleton(() => Test108Bloc());
  locator.registerLazySingleton(() => Test109Bloc());
  locator.registerLazySingleton(() => Test110Bloc());
  locator.registerLazySingleton(() => Test111Bloc());
  locator.registerLazySingleton(() => Test112Bloc());
  locator.registerLazySingleton(() => Test113Bloc());
  locator.registerLazySingleton(() => Test114Bloc());
  locator.registerLazySingleton(() => Test115Bloc());
  locator.registerLazySingleton(() => Test116Bloc());
  locator.registerLazySingleton(() => Test117Bloc());
  locator.registerLazySingleton(() => Test118Bloc());
  locator.registerLazySingleton(() => Test119Bloc());
  locator.registerLazySingleton(() => Test120Bloc());
  locator.registerLazySingleton(() => Test121Bloc());
  locator.registerLazySingleton(() => Test122Bloc());
  locator.registerLazySingleton(() => Test123Bloc());
  locator.registerLazySingleton(() => Test124Bloc());
  locator.registerLazySingleton(() => Test125Bloc());
  locator.registerLazySingleton(() => Test126Bloc());
  locator.registerLazySingleton(() => Test127Bloc());
  locator.registerLazySingleton(() => Test128Bloc());
  locator.registerLazySingleton(() => Test129Bloc());
  locator.registerLazySingleton(() => Test130Bloc());
  locator.registerLazySingleton(() => Test131Bloc());
  locator.registerLazySingleton(() => Test132Bloc());
  locator.registerLazySingleton(() => Test133Bloc());
  locator.registerLazySingleton(() => Test134Bloc());
  locator.registerLazySingleton(() => Test135Bloc());
  locator.registerLazySingleton(() => Test136Bloc());
  locator.registerLazySingleton(() => Test137Bloc());
  locator.registerLazySingleton(() => Test138Bloc());
  locator.registerLazySingleton(() => Test139Bloc());
  locator.registerLazySingleton(() => Test140Bloc());
  locator.registerLazySingleton(() => Test141Bloc());
  locator.registerLazySingleton(() => Test142Bloc());
  locator.registerLazySingleton(() => Test143Bloc());
  locator.registerLazySingleton(() => Test144Bloc());
  locator.registerLazySingleton(() => Test145Bloc());
  locator.registerLazySingleton(() => Test146Bloc());
  locator.registerLazySingleton(() => Test147Bloc());
  locator.registerLazySingleton(() => Test148Bloc());
  locator.registerLazySingleton(() => Test149Bloc());
  locator.registerLazySingleton(() => Test150Bloc());
}